from errors import *
from data import db_gacha
from objects.series import Series
import discord

types = {
    1: "Summoned",
    2: "Crafted",
    3: "Limited"
}

class Card:
    """
    A Card object to store information about a Card within
    a User's gacha inventory.    
    """
    def __init__(
        self, _id, _name, _acquired, _cost, _disenchant,
        _first_user, _full_url, _icon_url, _is_flagship,
        _is_exclusive, _points, _rating, _type, _series_id,
        _submitter
    ):
        self.id = _id
        self.name = _name
        self.acquired = _acquired
        self.cost = _cost
        self.disenchant = _disenchant
        self.first_user = _first_user
        self.full_url = _full_url
        self.icon_url = _icon_url
        self.is_flagship = _is_flagship
        self.is_exclusive = _is_exclusive
        self.points = _points
        self.rating = _rating
        self.type = _type
        self.series_id = _series_id
        self.submitter = _submitter

    def make_embed(self):
        e = discord.Embed(title=self.name, color=0xff1155)
        e.set_image(url=self.full_url)

        # v = f"From **{self.series.name}**\n" # TODO: Make series objects
        v = f"From **placeholder series**\n"
        
        if self.is_exclusive:
            v += "**[IPM-Exclusive]**"

        v += f"Card Type: **{types[self.type]}**\n"
        v += f"Banish Gain: **{self.disenchant}** 💎 | Summon Cost: **{self.cost}** 💎\n"
        a = f"Yes, first by {self.first_user}" if self.acquired else "No"
        v += f"Acquired? **{a}**"

        e.add_field(name=self.rating*'⭐', value=v)
        return e

    def __repr__(self):
        return f"Card({self.id})"

    @classmethod
    def get_from_dict(cls, dictionary):
        """
        Initializes a Card object from a dictionary
        generated by the Google Sheets API.

        Args:
            dictionary (dict): dictionary from Google Sheets.
        """
        return cls(
            dictionary["card_id"], 
            dictionary["card_name"], 
            bool(dictionary["card_acquired"]), 
            dictionary["card_cost"], 
            dictionary["card_disenchant"], 
            dictionary["card_user"], 
            dictionary["card_full_url"], 
            dictionary["card_icon_url"], 
            bool(dictionary["card_is_flagship"]), 
            bool(dictionary["card_is_exclusive"]), 
            dictionary["card_points"], 
            dictionary["card_rating"], 
            dictionary["card_type"], 
            dictionary["card_series_id"], 
            dictionary["card_submitter"]
        )

    @classmethod
    def get_from_db(cls, dictionary):
        """
        Initializes a Card object from a dictionary
        generated by the GachaHelper DB.

        Args:
            dictionary (dict): dictionary from GachaHelper results.
        """
        return cls(
            dictionary["card_id"], 
            dictionary["card_name"], 
            bool(dictionary["card_acquired"]), 
            dictionary["card_cost"], 
            dictionary["card_disenchant"], 
            dictionary["card_user"], 
            dictionary["card_full_url"], 
            dictionary["card_icon_url"], 
            bool(dictionary["card_is_flagship"]), 
            bool(dictionary["is_exclusive"]), 
            dictionary["card_points"], 
            dictionary["card_rating"], 
            dictionary["card_type"], 
            dictionary["card_series_id"], 
            dictionary["card_submitter"]
        )

    @classmethod
    def get_from_id(cls, card_id):
        """
        Initializes a Card object from an ID.

        Args:
            card_id (int): ID of the Card you wish to fetch.
        """
        db = db_gacha.GachaHelper(False)
        db.connect()
        result = db.get_card(card_id)
        db.close()
        return result

    @classmethod
    def get_from_name(cls, card_name):
        """
        Initializes a Card object from a name.

        Args:
            card_name (str): Name of the Card you wish to fetch.
        """
        db = db_gacha.GachaHelper(False)
        db.connect()
        result = db.get_card_from_name(card_name)
        db.close()
        return result